---

name: Lint

on:
  push:
    branches: [latest, main]
    paths:
      - '**.py'
      - '.github/workflows/lint.yml'
      - 'requirements_lint.txt'
  pull_request:
    branches: [latest, main]
    paths:
      - '**.py'
      - '.github/workflows/lint.yml'
      - 'requirements_lint.txt'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements_lint.txt
          pip install -r dns/requirements.txt
          pip install -r web_crawler/requirements.txt
          pip install -r ips/requirements.txt
        shell: bash

      - name: Running PyLint
        run: |
          pylint --version
          pylint --recursive=y .
        shell: bash
